name: Deploy Angular Project to GitHub Pages

on: [push]
#jobs:
 # build-and-deploy:
  #  concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.

permissions:
  contents: read
  pages: write
  id-token: write

env:
  GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN_SECRET }}

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: npm run build --prod

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./ourNewApp-Group1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1      

  deploy:
    environment:
      name: github-pages
      url: ${{ cejas1719.github.io/OurNewApp-Group1 }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1






      # - name: Print ACCESS_TOKEN_SECRET
      #   run: echo "ACCESS_TOKEN_SECRET is ${{ secrets.ACCESS_TOKEN_SECRET }}"

      # - name: Print GITHUB_TOKEN
      #   run: echo "GITHUB_TOKEN is ${{ env.GITHUB_TOKEN }}"
      
      # - name: Deploy to Gitpages
      #   uses: JamesIves/github-pages-deploy-action@releases/v3
      #   with:
      #     ACCESS_TOKEN: ${{ env.ACCESS_TOKEN_SECRET }}
      #     BRANCH: gh-pages
      #     FOLDER: dis